### ISSUE TITLE
Cannot download database error

### ISSUE THREAD

**Issue by the-lazy-fox** [crazy-max/geoip-updater#96]
### Behaviour

The container is in error and not refreshing the dbs.

#### Steps to reproduce this issue

Start with docker compose:
```
  geoip-updater:
    container_name: rutorrent-main-geoip-updater
    image: crazymax/geoip-updater:latest
    restart: unless-stopped
    depends_on:
      vpn:
        condition: service_healthy
    env_file:
      - /home/thelazyfox/docker/media-center/rutorrent-main/geoip-updater.env
    volumes:
      - /home/thelazyfox/docker/media-center/rutorrent-main/data/geoip:/data
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - deunhealth.restart.on.unhealthy=true
```
ENV file
```
TZ=Europe/Zurich
EDITION_IDS=GeoLite2-City,GeoLite2-Country
LICENSE_KEY=123456789
DOWNLOAD_PATH=/data
SCHEDULE="0 0 * * 0"
LOG_LEVEL=debug
LOG_JSON=false
```

#### Expected behaviour

> Should work without issues

#### Actual behaviour

> It doesn't work and log are full of errors

### Configuration

* geoip-updater version : 1.5.0
* geoip-updater command (without sensitive data): Docker container
* Platform (windows/linux) : Linux

### Logs

```
Sat, 08 Jan 2022 13:56:58 CET INF Starting geoip-updater 1.5.0

Sat, 08 Jan 2022 13:56:58 CET ERR Cannot download database error="Cannot get archive checksum: Received invalid status code 401: {%!s(*http.http2clientStream=&{0xc0001b6180 0xc00011e000 <nil> <nil> 1 {{0 0} {{} 0xc0001b64b0 {0 0 0 <nil> <nil>} 824635516136} 0xc000356080 0 0xc00010c0f0 <nil> <nil> 0x6a3f00} true false {0 {0 0}} 0xc00033d500 <nil> 0xc00033d4a0 0xc00033d5c0 <nil> 0xc00033d560 0xc0000d2000 {[] 65536 0xc0001b61e0} {[] 4194284 0xc0001b61f0} 20 <nil> <nil> 0 true true true true true false 0 true false map[] 0xc0000d2078})}" edition_id=GeoLite2-City

Sat, 08 Jan 2022 13:56:59 CET ERR Cannot download database error="Cannot get archive checksum: Received invalid status code 401: {%!s(*http.http2clientStream=&{0xc0001b6180 0xc00011e000 <nil> <nil> 3 {{0 0} {{} 0xc0000f2030 {0 0 0 <nil> <nil>} 824634712168} 0xc000356280 0 0xc00010c0f0 <nil> <nil> 0x6a3f00} true false {0 {0 0}} 0xc0000cc0c0 <nil> 0xc0000cc060 0xc0000cc180 <nil> 0xc0000cc120 0xc0000d2120 {[] 65536 0xc0001b61e0} {[] 4194284 0xc0001b61f0} 20 <nil> <nil> 0 true true true true true false 0 true false map[] 0xc0000d2198})}" edition_id=GeoLite2-Country

Sat, 08 Jan 2022 13:56:59 CET INF Cron initialized with schedule 0 0 * * 0

Sat, 08 Jan 2022 13:56:59 CET INF Next run in 10 hours 3 minutes (2022-01-09 00:00:00 +0100 CET)
```
